AMQP_URI: !raw_env_var 'amqp://${NAMEKO_USER}:${NAMEKO_PASSWORD}@${RMQ_ADDRESS}:5672/${NAMEKO_VHOST}'
WEB_SERVER_ADDRESS: '${RMQ_ADDRESS}:15672'
rpc_exchange: 'nameko-rpc'
max_workers: 1
parent_calls_tracked: 10

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]
