terms:
 - id: Contact Person
   term: Contact Person
   active: true
 - id: Data Collector
   term: Data Collector
   active: true
 - id: Data Curator
   term: Data Curator
   active: true
 - id: Data Manager
   term: Data Manager
   active: true
 - id: Distributor
   term: Distributor
   active: true
 - id: Editor
   term: Editor
   active: true
 - id: Hosting Institution
   term: Hosting Institution
   active: true
 - id: Producer
   term: Producer
   active: true
 - id: Project Leader
   term: Project Leader
   active: true
 - id: Project Manager
   term: Project Manager
   active: true
 - id: Project Member
   term: Project Member
   active: true
 - id: Registration Agency
   term: Registration Agency
   active: true
 - id: Registration Authority
   term: Registration Authority
   active: true
 - id: Related Person
   term: Related Person
   active: true
 - id: Researcher
   term: Researcher
   active: true
 - id: Research Group
   term: Research Group
   active: true
 - id: Rights Holder
   term: Rights Holder
   active: true
#  kept as `active: false` (i.e. not to display/chose from)
#  else if any record was previously saved with this it would break the app
 - id: Sponsor Supervisor
   term: Sponsor Supervisor
   active: false
 - id: Sponsor
   term: Sponsor
   active: true
 - id: Supervisor
   term: Supervisor
   active: true
 - id: Work Package Leader
   term: Work Package Leader
   active: true
 - id : Other
   term: Other
   active:  true  
