terms:
  - id: British Library
    term: British Library
  - id: British Museum
    term: British Museum
  - id: MOLA
    term: MOLA
  - id: National Museums of Scotland
    term: National Museums of Scotland
  - id: TATE
    term: TATE
