terms:
    - id: https://creativecommons.org/licenses/by/4.0/
      term: CC BY 4.0 Attribution
      active: true
    - id: https://creativecommons.org/licenses/by-nc/4.0/
      term: CC BY-NC 4.0 Attribution-NonCommercial
      active: true
    - id: https://creativecommons.org/licenses/by-sa/4.0/
      term: CC BY-SA 4.0 Attribution ShareAlike
      active: true
    - id: https://creativecommons.org/licenses/by-nd/4.0/
      term: CC BY-ND 4.0 Attribution NoDerivs
      active: true
    - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
      term: CC BY-NC-SA 4.0 Attribution-NonCommercial-ShareAlike
      active: true
    - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
      term: CC BY-NC-ND 4.0 Attribution NonCommercial-NoDerivs
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal Public Domain
      active: true
    - id: https://opensource.org/licenses/MIT
      term: MIT
      active: true
    - id: https://www.gnu.org/licenses/old-licenses/gpl-1.0.html
      term: GPL
      active: true
    - id: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
      term: GPL 2.0+
      active: true
    - id: https://www.gnu.org/licenses/gpl-3.0.en.html
      term: GPL 3.0+
      active: true
    - id: https://www.apache.org/licenses/LICENSE-2.0
      term: Apache 2.0
      active: true
    - id: https://opendatacommons.org/licenses/odbl/1.0/
      term: ODBL
      active: true
    - id: https://www.mozilla.org/en-US/MPL/2.0/
      term: Mozilla Public License (MPL)
      active: true
    - id: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
      term: Open Government Licence (OGL)
      active: true