version: '2'

volumes:
  certs:
  certs-data:
  self-signed:

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  web:
    build:
      context: ../.
      dockerfile: Dockerfile
    volumes:
      - web:/data/tmp/uploads
      - ..:/data
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - zoo2
      - zoo3
      - memcache
    expose:
      - 3000
    env_file:
      - credentials-dev.env
    networks:
      internal:

  web_server:
    build:
      context: ../.
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - web
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
      external:
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - self-signed:/etc/selfsigned
      - ./docker/shibboleth:/data/shibboleth
      - ./docker/web_server_env.sh:/data/web_server_env.sh

